# Generated by Django 3.0.4 on 2020-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimg',
            field=models.ImageField(default='', upload_to='post_pics', verbose_name='Post Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='#general', max_length=20),
        ),
    ]
