# Generated by Django 3.0.4 on 2020-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200626_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(blank=True, default='', upload_to='post_pics', verbose_name='Post Image'),
        ),
    ]
