# Generated by Django 3.0.4 on 2020-07-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_microtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pexels.com%2Fsearch%2Fcode%2F&psig=AOvVaw0EunvRbdSI-aglYlkKXB3q&ust=1594244868941000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLjI0ouPvOoCFQAAAAAdAAAAABAD', upload_to='post_pics', verbose_name='Post Image'),
        ),
    ]
