# Generated by Django 3.0.4 on 2020-07-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200708_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(default='defpost.png', upload_to='post_pics', verbose_name='Post Image'),
        ),
    ]
