# Generated by Django 3.0.4 on 2020-07-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200708_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='githubreop',
            new_name='githubrepo',
        ),
    ]
