# Generated by Django 3.0.6 on 2020-05-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200525_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rollno',
            field=models.CharField(default='1XAG1A0XXX', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
