# Generated by Django 3.0.6 on 2020-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200525_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_classrep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hey, I am new to Ace Students'),
        ),
    ]
