# Generated by Django 3.0.6 on 2020-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200525_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeDetails',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This is fun'),
        ),
    ]
