# Generated by Django 3.0.6 on 2020-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200525_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(default='1XAG1A0XXX', max_length=10)),
                ('is_cr', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_classrep',
        ),
    ]
