# Generated by Django 3.0.6 on 2020-05-26 08:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200525_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedatabase',
            name='clg_name',
            field=models.CharField(default=' ', max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='is_cr',
            field=models.BooleanField(default=False, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='collegedatabase',
            name='rollno',
            field=models.CharField(default='1XAG1A0XXX', max_length=10, verbose_name=django.contrib.auth.models.User),
        ),
    ]
