# Generated by Django 3.0.4 on 2020-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200609_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_img',
            field=models.ImageField(default='default.png', upload_to='bg_profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This is fun'),
        ),
    ]
