# Generated by Django 3.0.4 on 2020-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200609_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I really need to change my bio'),
        ),
    ]
