# Generated by Django 3.0.4 on 2020-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200626_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hey, I am new to Ace Students'),
        ),
    ]
