# Generated by Django 3.0.4 on 2020-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200626_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This is fun'),
        ),
    ]
