# Generated by Django 3.0.4 on 2020-07-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200708_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comp_prog',
            field=models.URLField(blank=True, help_text='Any Competitve programming profile (ProjectEuler, Hackerrank , Hackerearth ...)', verbose_name='Competitve Coding'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, verbose_name='Github/Gitlab'),
        ),
    ]
