# Generated by Django 3.0.4 on 2020-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200708_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_img',
            field=models.ImageField(default='defpfpbck.png', upload_to='bg_profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hello people'),
        ),
    ]
